---
# Source: fluent-bit/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  release-name-fluent-bit
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: fluent-bit
    helm.sh/chart: fluent-bit-0.4.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: fluent-bit
automountServiceAccountToken: true
---
# Source: fluent-bit/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-fluent-bit-config
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: fluent-bit
    helm.sh/chart: fluent-bit-0.4.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: fluent-bit
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
    
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        LogLevel     info
        Config_Watch On
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
    
    [INPUT]
        Name cpu
    
    
    [OUTPUT]
        Name  stdout
        Match *
---
# Source: fluent-bit/templates/service.yml
apiVersion: v1
kind: Service
metadata:
  name:  release-name-fluent-bit
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: fluent-bit
    helm.sh/chart: fluent-bit-0.4.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: fluent-bit
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      port: 2020
      targetPort: 2020
      nodePort: null
  selector:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/part-of: fluent-bit
---
# Source: fluent-bit/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  release-name-fluent-bit
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: fluent-bit
    helm.sh/chart: fluent-bit-0.4.8
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: fluent-bit
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: release-name
  replicas: 1
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        helm.sh/chart: fluent-bit-0.4.8
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: fluent-bit
    spec:
      
      priorityClassName: ""
      serviceAccountName: release-name-fluent-bit
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: fluent-bit
                    app.kubernetes.io/instance: release-name
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      initContainers:
      containers:
        - name: fluent-bit
          image: docker.io/bitnami/fluent-bit:2.1.7-debian-11-r0
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
            - name: http
              containerPort: 2020
          env:
          envFrom:
          startupProbe:
            failureThreshold: 15
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              port: http
              path: /api/v1/health
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              port: http
              path: /api/v1/health
          readinessProbe:
            failureThreshold: 15
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            httpGet:
              port: http
              path: /api/v1/health
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: config
              mountPath: /opt/bitnami/fluent-bit/conf/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: config
              mountPath: /opt/bitnami/fluent-bit/conf/custom_parsers.conf
              subPath: custom_parsers.conf
      volumes:
        - name: config
          configMap:
            name: release-name-fluent-bit-config
