---
# Source: haproxy/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-haproxy
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.8.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
automountServiceAccountToken: true
---
# Source: haproxy/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-haproxy
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.8.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 1024
    defaults
      log global
      timeout client 60s
      timeout connect 60s
      timeout server 60s
    frontend fe_main
      bind :8080
      default_backend be_main
    backend be_main
      server web1 10.0.0.1:8080 check
---
# Source: haproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-haproxy
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.8.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  loadBalancerSourceRanges: []
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: haproxy
---
# Source: haproxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-haproxy
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: haproxy
    helm.sh/chart: haproxy-0.8.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: haproxy
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: haproxy
  template:
    metadata:
      annotations:
        checksum/configmap: e616f6b0612704bf28f2fc7df2cb9f025b6b401b3dc0561afa7d4ad527e772d7
      labels:
        app.kubernetes.io/name: haproxy
        helm.sh/chart: haproxy-0.8.5
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: haproxy
    spec:
      serviceAccountName: release-name-haproxy
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: haproxy
                    app.kubernetes.io/instance: release-name
                    app.kubernetes.io/component: haproxy
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: haproxy
          image: docker.io/bitnami/haproxy:2.8.1-debian-11-r3
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          ports:
            - containerPort: 8080
              name: http
          env:
          envFrom:
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            # Using exec instead of tcpSocket to avoid noise in te logs
            exec:
              command:
                - pgrep
                - haproxy
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            # Using exec instead of tcpSocket to avoid noise in te logs
            exec:
              command:
                - pgrep
                - haproxy
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:
            - name: haproxy-conf
              mountPath: /bitnami/haproxy/conf
      volumes:
        - name: haproxy-conf
          configMap:
            name: release-name-haproxy
