---
# Source: jenkins/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: jenkins/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  jenkins-password: "Z1VSMG5wZ0JpZQ=="
---
# Source: jenkins/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"
---
# Source: jenkins/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
rules:
---
# Source: jenkins/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-jenkins
subjects:
  - kind: ServiceAccount
    name: release-name-jenkins
    namespace: "harbor"
---
# Source: jenkins/templates/controller-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: jenkins-controller
---
# Source: jenkins/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-jenkins
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-12.2.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/instance: release-name
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        helm.sh/chart: jenkins-12.2.5
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: jenkins-controller
      annotations:
        checksum/secrets: c0892f8bd4b7aa72006f83dd9719c0a9af42846b55987994a6f883a92a7d87b4
    spec:
      serviceAccountName: release-name-jenkins
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: jenkins
                    app.kubernetes.io/instance: release-name
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: jenkins
          image: docker.io/bitnami/jenkins:2.401.2-debian-11-r6
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BITNAMI_DEBUG
              value: "false"
            - name: JENKINS_USERNAME
              value: "user"
            - name: JENKINS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: release-name-jenkins
                  key: jenkins-password
            - name: JENKINS_HOME
              value: "/bitnami/jenkins/home"
            - name: JENKINS_SKIP_BOOTSTRAP
              value: "no"
            - name: JENKINS_HOST
              value: ""
            - name: JENKINS_EXTERNAL_HTTP_PORT_NUMBER
              value: "80"
            - name: JENKINS_EXTERNAL_HTTPS_PORT_NUMBER
              value: "443"
            - name: JENKINS_PLUGINS_LATEST
              value: "true"
            - name: JENKINS_PLUGINS_LATEST_SPECIFIED
              value: "false"
            - name: JENKINS_SKIP_IMAGE_PLUGINS
              value: "false"
            - name: JENKINS_OVERRIDE_PLUGINS
              value: "false"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits: {}
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: jenkins-data
              mountPath: /bitnami/jenkins
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: release-name-jenkins
