---
# Source: kubernetes-event-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-kubernetes-event-exporter
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.4.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: kubernetes-event-exporter/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-kubernetes-event-exporter
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.4.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
  config.yaml: |
    leaderElection: {}
    logFormat: pretty
    logLevel: debug
    receivers:
    - file:
        layout: {}
        path: /dev/stdout
      name: dump
    route:
      routes:
      - match:
        - receiver: dump
---
# Source: kubernetes-event-exporter/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-kubernetes-event-exporter-harbor
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.4.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
# Source: kubernetes-event-exporter/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-kubernetes-event-exporter-harbor
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.4.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-name-kubernetes-event-exporter-harbor
subjects:
  - kind: ServiceAccount
    name: release-name-kubernetes-event-exporter
    namespace: "harbor"
---
# Source: kubernetes-event-exporter/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-kubernetes-event-exporter
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    helm.sh/chart: kubernetes-event-exporter-2.4.5
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: kubernetes-event-exporter
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-event-exporter
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        checksum/config: 8e884f71ca7aa75b920d552840517d42c7cc5e2deb798db4261fd4c8ee198c9b
      labels:
        app.kubernetes.io/name: kubernetes-event-exporter
        helm.sh/chart: kubernetes-event-exporter-2.4.5
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: kubernetes-event-exporter
    spec:
      serviceAccountName: release-name-kubernetes-event-exporter
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: kubernetes-event-exporter
                    app.kubernetes.io/instance: release-name
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
      containers:
        - name: event-exporter
          image: docker.io/bitnami/kubernetes-event-exporter:1.1.0-debian-11-r68
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: []
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          args:
            - -conf=/data/config.yaml
          resources:
            limits: {}
            requests: {}
          ports:
            - name: http
              containerPort: 2112
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: cfg
      volumes:
        - name: cfg
          configMap:
            name: release-name-kubernetes-event-exporter
