---
# Source: nats/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-name-nats
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: nats
    helm.sh/chart: nats-7.8.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
data:
  nats-server.conf: |-
    CnNlcnZlcl9uYW1lOiAkTkFUU19TRVJWRVJfTkFNRQpsaXN0ZW46IDAuMC4wLjA6NDIyMgpodHRwOiAwLjAuMC4wOjgyMjIKCiMgQXV0aG9yaXphdGlvbiBmb3IgY2xpZW50IGNvbm5lY3Rpb25zCmF1dGhvcml6YXRpb24gewogIHVzZXI6ICJuYXRzX2NsaWVudCIKICBwYXNzd29yZDogImc4WWRlcGRZMEIiCiAgdGltZW91dDogIDEKfQoKIyBMb2dnaW5nIG9wdGlvbnMKZGVidWc6IGZhbHNlCnRyYWNlOiBmYWxzZQpsb2d0aW1lOiBmYWxzZQojIFBpZCBmaWxlCnBpZF9maWxlOiAiL29wdC9iaXRuYW1pL25hdHMvdG1wL25hdHMtc2VydmVyLnBpZCIKCiMgU29tZSBzeXN0ZW0gb3ZlcnJpZGVzCgojIENsdXN0ZXJpbmcgZGVmaW5pdGlvbgpjbHVzdGVyIHsKICBuYW1lOiAibmF0cyIKICBsaXN0ZW46IDAuMC4wLjA6NjIyMgogICMgQXV0aG9yaXphdGlvbiBmb3IgY2x1c3RlciBjb25uZWN0aW9ucwogIGF1dGhvcml6YXRpb24gewogICAgdXNlcjogIm5hdHNfY2x1c3RlciIKICAgIHBhc3N3b3JkOiAicUZxbzBzZ3U2UyIKICAgIHRpbWVvdXQ6ICAxCiAgfQogICMgUm91dGVzIGFyZSBhY3RpdmVseSBzb2xpY2l0ZWQgYW5kIGNvbm5lY3RlZCB0byBmcm9tIHRoaXMgc2VydmVyLgogICMgT3RoZXIgc2VydmVycyBjYW4gY29ubmVjdCB0byB1cyBpZiB0aGV5IHN1cHBseSB0aGUgY29ycmVjdCBjcmVkZW50aWFscwogICMgaW4gdGhlaXIgcm91dGVzIGRlZmluaXRpb25zIGZyb20gYWJvdmUKICByb3V0ZXMgPSBbCiAgICBuYXRzOi8vbmF0c19jbHVzdGVyOnFGcW8wc2d1NlNAcmVsZWFzZS1uYW1lLW5hdHM6NjIyMgogIF0KfQ==
---
# Source: nats/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nats-headless
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: nats
    helm.sh/chart: nats-7.8.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-client
      port: 4222
      targetPort: client
    - name: tcp-cluster
      port: 6222
      targetPort: cluster
    - name: tcp-monitoring
      port: 8222
      targetPort: monitoring
  selector: 
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: release-name
---
# Source: nats/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-nats
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: nats
    helm.sh/chart: nats-7.8.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: tcp-client
      port: 4222
      targetPort: client
      nodePort: null
    - name: tcp-cluster
      port: 6222
      targetPort: cluster
      nodePort: null
    - name: tcp-monitoring
      port: 8222
      targetPort: monitoring
      nodePort: null
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: release-name
---
# Source: nats/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-nats
  namespace: "harbor"
  labels:
    app.kubernetes.io/name: nats
    helm.sh/chart: nats-7.8.6
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: release-name
  serviceName: release-name-nats-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
        helm.sh/chart: nats-7.8.6
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/managed-by: Helm
      annotations:
        checksum/secret: b08452287c37c59cec7051e0d6c7a93f685f3f28bf931a15fc07e930a5862906
    spec:
      
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: nats
                    app.kubernetes.io/instance: release-name
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      containers:
        - name: nats
          image: docker.io/bitnami/nats:2.9.20-debian-11-r0
          imagePullPolicy: IfNotPresent
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: NATS_FILENAME
              value: "nats-server"
            - name: NATS_SERVER_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: client
              containerPort: 4222
            - name: cluster
              containerPort: 6222
            - name: monitoring
              containerPort: 8222
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: monitoring
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: monitoring
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: config
              mountPath: /bitnami/nats/conf/nats-server.conf
              subPath: nats-server.conf
      volumes:
        - name: config
          secret:
            secretName: release-name-nats
